### PR TITLE
Better user error.

### LINKED ISSUE #121: Add error handler when action is not a function
If an action is set in the component vuex property as undefined, Vuex will throw an `Uncaught TypeError: Cannot read property 'call' of undefined`. This can happen when importing actions which names have been changed. A better indication of the Action trying to be called and failed would be more helpful.

### PR DESCRIPTION
**Pull request by zigomir**
Proposal on how to fix #121. Feedback appreciated.

### CODE REVIEW

File: src/override.js [hunk 1]
```diff
@@ -126,11 +126,16 @@ export default function (Vue) {
...
    * @param {Store} store
    * @param {Function} action
+   * @param {String} key
    */
 
-  function makeBoundAction (store, action) {
+  function makeBoundAction (store, action, key) {
     return function vuexBoundAction (...args) {
-      return action.call(this, store, ...args)
+      if (Function.prototype.isPrototypeOf(action)) {
```
Comment (yyx990803) [inline src/override.js]: I think just `typeof action === 'function'` is simpler.

File: src/override.js [hunk 2]
```diff
@@ -126,11 +126,16 @@ export default function (Vue) {
...
+        return action.call(this, store, ...args)
+      }
+
+      throw new Error(`Action bound to key 'vuex.actions.${key}' is not a function.`)
```
Comment (yyx990803) [inline src/override.js]: Should use `console.warn('[vuex] ...')` to keep things consistent.

Comment (zigomir) [inline src/override.js]: Any idea how we'd test that case?

Comment (yyx990803) [inline src/override.js]: You can use a spy on `console.warn` (which means we need Sinon)

Comment (zigomir) [inline src/override.js]: Cool. I added sinon to spy on console.warn.

File: src/override.js [hunk 3]
```diff
@@ -126,11 +126,16 @@ export default function (Vue) {
    *
    * @param {Store} store
    * @param {Function} action
+   * @param {String} key
    */
 
-  function makeBoundAction (store, action) {
+  function makeBoundAction (store, action, key) {
     return function vuexBoundAction (...args) {
```
Comment (yyx990803) [inline src/override.js]: actually, we should do the `typeof action` check and warn in `makeBoundAction` before returning the bound action. This way the user gets the warning right at instance creation time instead of when they actually call the action.

Comment (zigomir) [inline src/override.js]: You're right! I just pushed a fix.

**Comment by yyx990803** [comment]
👍
